### ISSUE TITLE
Can not get this to Autoroute with Symfony 4.4

### ISSUE THREAD

**Issue by taleteller** [rollerworks/RouteAutowiringBundle#14]
I am trying to get your Bundle working with Symfony 4.4 LTS. Since version 1.2 depends on Symfony 5.0 i am refering to 1.1 in this ticket. 

Installations works fine, classes seem to get registered and loaded as expected. The Bundle I am trying this gets loaded as well, others resources as `services.yaml`work fine. 

I am loading route resources as described in the README.md inside the `MyBundleExtension::load()` method: 
```
$routeImporter = new RouteImporter($container,'administration');
$routeImporter->addObjectResource($this);
$routeImporter->import('@PSPAdministrationModule/Resources/config/routing.yaml');
```
Execution and compiling seem to work fine as well, I can trace `RouteAutowiringPass` to happen as it seems to be expected. However this does not to lead to any routes at all. `bin/console debug:router` does come up as before. I want to use annotations for routing and cross referenced [HarmonyCMS](https://github.com/harmonycms/core-bundle) for clues. 

The `routing.yaml` consists of 
```
controllers:
  resource: '../../Controller'
  type: annotation
```
and the mentioned Controller contains a matching Annotation:
```
    /**
     * @Route("/administration/api/userlist", name="administration_userlist")
     */
    public function getUserList(Request $request) { ...
```
However it seems, no matter of annotations or regular routes, the `routing.yaml` seems not even being interpreted. Even clearly malformed code in this file does not seem to trigger any reaction at all. Same goes for `$routeImporter->addResource()` with a full path. I can see the resource to be integrated but not being executed at all. Its no typo in the paths, I checked them twenty times over.

**Comment by taleteller** [comment]
Is this project abandoned? If so, I might implement my own solution.

**Comment by sstok** [comment]
Not abandoned (otherwise I would archive it), but I keep forgetting to check my GitHub notifications.

**Comment by sstok** [comment]
The Autowiring route-loader will register the routes in an internal collection (called routing-slot in this bundle), you will need to import the actual routing-slot somewhere (as you would normally would with a routing config file). The main focus is to import routes into a slot without having to change the importer file.

https://github.com/rollerworks/RouteAutowiringBundle#loading-registered-routes

```yaml
# app/config/routing.yml

_administration:
    resource: administration"
    type: rollerworks_autowiring
    prefix:   /
```

**Comment by taleteller** [comment]
Meanwhile I found a more elegant solutions with Symfony, since some time it supports "double globs" for traversing subdirectories, extending the kernel this way, does the job:

```#kernel.php
protected function configureRoutes(RouteCollectionBuilder $routes): void
{
    ...
    $modulesDir = $this->getProjectDir().'/modules';
    $routes->import( $modulesDir.'/**/src/Resources/config/{routes}'.self::CONFIG_EXTS, '/', 'glob');
}
```
Route files are simply standard ...

```#routes.yaml
controllers:
  resource: '../../Controller'
  type: annotation
```
Other services have to be loaded in the Extension anyway, therefore I have no longer demand for your Bundle.

**Comment by sstok** [comment]
Indeed. Symfony has added better support for this 👍😛
